### ISSUE TITLE
Schema entidad

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#10]
https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/blob/94be8d992df2d3b2cd89a4600531d06172f6df13/graphSource/json2rdf.py#L24

De momento pon el https://schema.org/Organization

**Comment by JonAnderAsua** [comment]
Cambiado
