### ISSUE TITLE
Properties normalizadas (Y alguna duda)

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#11]
- http://ehu.eus/prop/relations/takes_part : https://schema.org/participant
- http://ehu.eus/prop/relations/mentions : https://schema.org/mentions
- http://ehu.eus/prop/relations/beneficiary_of : http://ehu.eus/transparentrelations#beneficiary_of
- http://ehu.eus/prop/relations/parent : https://schema.org/parent
- http://ehu.eus/prop/relations/pays : http://ehu.eus/transparentrelations#pays_to
- http://ehu.eus/prop/relations/has_bank_account_in : http://ehu.eus/transparentrelations#has_bank_account_in
- http://ehu.eus/prop/relations/authors : https://schema.org/author (Inversa!)
- http://ehu.eus/prop/relations/works_for : https://schema.org/worksFor
- http://ehu.eus/prop/relations/registered_in : http://ehu.eus/transparentrelations#registered_in
- http://ehu.eus/prop/relations/owns : https://schema.org/owns
- http://ehu.eus/prop/relations/controls : http://ehu.eus/transparentrelations#controls
- http://ehu.eus/prop/relations/spouse : https://schema.org/spouse
- http://ehu.eus/prop/relations/knows : https://schema.org/knows 
- http://ehu.eus/prop/relations/happens_in : http://ehu.eus/transparentrelations#takes_place_in
- <http://ehu.eus/id/person/mohamed_vi> <http://ehu.eus/prop/relations/gives> <http://ehu.eus/id/place/marrakech> . ???
- http://ehu.eus/prop/relations/manages : http://ehu.eus/transparentrelations#manages

**Comment by mikel-egana-aranguren** [comment]
Cambiar en el programa, no añadir triples nuevos

**Comment by JonAnderAsua** [comment]
He cambiado las relaciones y el triple que daba problemas no lo he añadido, si no lo ves no está

**Comment by mikel-egana-aranguren** [comment]
Que triple daba problemas?

**Comment by JonAnderAsua** [comment]
El de Mohamed, si te fijas a la hora de añadir el triple miro 2 cosas, la primera es ver si el triple está en el grafo ya y la otra es mirar a ver si el triple es ese o no

**Comment by mikel-egana-aranguren** [comment]
No entiendo nada de lo que pones. Tienes que poner enlaces al codigo o al archivo con el grafo, como te puse yo:

![image](https://user-images.githubusercontent.com/3883671/155536480-27fa495f-8eba-426e-9879-f29c2921faed.png)

¿Por qué tienes que mirar si esta ya en grafo?

**Comment by JonAnderAsua** [comment]
Para que no se repitan triples, dudo que pase pero no cuesta nada comprobar ese caso

**Comment by mikel-egana-aranguren** [comment]
Los triples no se repiten. Si es el mismo triple, simplemente lo "pisa". Si es un triple diferente, entonces deberia estar en el grafo

**Comment by JonAnderAsua** [comment]
Vale, ya está cambiado
