### ISSUE TITLE
Subir RDF a GraphDB mediante RDFLib

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#13]

**Comment by JonAnderAsua** [comment]
Estoy probando a hacerlo en localhost antes de subirlo al servidor, hay dos formas, una usando la API propia mediante comandos y otra usando SPARQLWrapper, la primera no da errores pero no consigue subirlo y la segunda falla. Lo seguiré mirando si no a ver si me puedes ayudar tú en la reunión del miércoles

**Comment by JonAnderAsua** [comment]
Tienes que abrir el puerto 7200 del servidor

**Comment by JonAnderAsua** [comment]
He estado todo el día mirando el error que daba la eskaera SPARQL y soy incapaz de solucionar nada

**Comment by JonAnderAsua** [comment]
He conseguido limpiar los carácteres ocultos y no da problemas a la hora de subir las cosas, cierro el issue
