### ISSUE TITLE
Crear logs

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#16]

**Comment by JonAnderAsua** [comment]
Los crea

**Comment by mikel-egana-aranguren** [comment]
y los destruye

https://realpython.com/python-logging/#the-logging-module

**Comment by JonAnderAsua** [comment]
Los crea (esta vez usando la librería que me dijiste) así que cierro este issue
