### ISSUE TITLE
Dar acceso a servidor Moore a Jon Ander

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#2]

**Comment by mikel-egana-aranguren** [comment]
Hecho. 

@JonAnderAsua tienes graphdb en el repo: https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/tree/develop/graphdb-silk-docker

Una vez dentro de Moore, te clonas el repo (Con LFS igual)

**Comment by JonAnderAsua** [comment]
Me tienes que añadir al grupo de docker

**Comment by mikel-egana-aranguren** [comment]
Hecho. Prueba ahora a ver

**Comment by mikel-egana-aranguren** [comment]
@JonAnderAsua has conseguido?
