### ISSUE TITLE
Añadir repo visualizacion como submodulo

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#21]

**Comment by JonAnderAsua** [comment]
Tutorial de como hacerlo: https://git-scm.com/book/es/v2/Herramientas-de-Git-Subm%C3%B3dulos

**Comment by JonAnderAsua** [comment]
Me he basado en el siguiente tutorial para hacerlo: https://devconnected.com/how-to-add-and-update-git-submodules/

Lo que básicamente había que hacer era usar el siguiente comando:
git add submodule <url de la repo>

Lo cierro pero lo dejo en revisión por si quieres echarle un vistazo
