### ISSUE TITLE
Hacer tutorial en README

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#25]

**Comment by JonAnderAsua** [comment]
Está hecho el tutorial en la rama feature_tutorial.  A la hora de hacer el merge me lo ha hecho directamente, no me ha dado la opción de hacer un pull request

**Comment by mikel-egana-aranguren** [comment]
Es que tienes que crear tu el pull request sin hacer el merge. Intenta crear un pull request de develop a main, y asignamelo a mi
