### ISSUE TITLE
Buscar dataset del Partido del Negocio Vasco que tenga conexion con la donacion 

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#27]

**Comment by JonAnderAsua** [comment]
He encontrado esto, es una página web que recopila muchísimos datos de casos de corrupción. Según ellos hay más de 500 casos y los separa por partidos, instituciones,... El problema está que no da los datos en ningún formato, habría que crearlo a mano, por lo demás es una mina de oro. https://casos-aislados.com/

**Comment by JonAnderAsua** [comment]
He mandado un correo a los de Casos Aislados para ver si tienen algún dataset que englobe todo, si me responden y me lo mandan lo subo aquí

**Comment by JonAnderAsua** [comment]
Ya que no me contestan a los correos que les he mandado he creado un pequeño dataset con uno de los casos que salen ahí, en la reunión de hoy te lo enseño y si le das el visto bueno lo implementamos en el proyecto

**Comment by JonAnderAsua** [comment]
Implementarlo con NLP para que pille datos de la siguiente URL https://casos-aislados.com/Caso-Aislado.php?Caso=Caso%20Balenciaga&numero=413

**Comment by JonAnderAsua** [comment]
Para descargar más datasets: https://offshoreleaks.icij.org/pages/database
