### ISSUE TITLE
Probar con diferentes Triple Stores

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#29]
Obligatorios:

- https://www.stardog.com/get-started/
- https://virtuoso.openlinksw.com/
- https://www.oxfordsemantic.tech/tryrdfoxforfree

Opcionales:
- https://jena.apache.org/documentation/tdb/
- https://rdf4j.org/
- https://aws.amazon.com/es/neptune/
- https://cambridgesemantics.com/anzograph/?utm_campaign=AnzoGraph&utm_source=anzographdotcom&utm_medium=redirect
- https://franz.com/

**Comment by JonAnderAsua** [comment]
He conseguido crear una instancia stardog pero a la hora de hacer eskaeras a su sparql endpoint me da errores de formato, a la tarde me ocupo de arreglar eso

**Comment by mikel-egana-aranguren** [comment]
Tienes que buscar la URL del SPARQL endpoint contra la que puedes hacer HTTP POSTs de consultas SPARQL. Normalmente suele ser `url_instancia/sparql`. Esa misma URL te va a servir para que crear el formulario SPARQL de cara al usuario

**Comment by JonAnderAsua** [comment]
He conseguido la parte de stardog... El problema estaba en la URI del endpoint. El Stardog existen dos tipos:
- URI para escribir: http://localhost:5820/myDB/update
- URI para leer http://localhost:5820/myDB/query
Una vez cambiado esto ya funciona... Siguiente paso, Virtuoso
https://community.stardog.com/t/stardog-sparql-endpoints/814

**Comment by JonAnderAsua** [comment]
De virtuoso tengo que instalar el Universal Server?
A todo esto, he estado mirando y todas las opciones que tiene son de pago (y no especialmente baratas)

**Comment by mikel-egana-aranguren** [comment]
Es Virtuoso Open Source: http://vos.openlinksw.com/owiki/wiki/VOS/VOSUbuntuNotes

**Comment by JonAnderAsua** [comment]
Virtuoso hecho, en este caso la URI de la triplestore es algo así:
http://localhost:8890/<Nombre de la DB>
En este caso ha sido así:
http://localhost:8890/LaDonacion
Siguiente paso el de Oxford Semantic

**Comment by JonAnderAsua** [comment]
De Oxford Semantic cual tengo que usar? En el link que me has puesto me sale para una prueba gratuita

**Comment by mikel-egana-aranguren** [comment]
La prueba gratuita

**Comment by JonAnderAsua** [comment]
Me he saltado el de Oxford y he instalado y comprobado Apache Jena.
Las URIs para hacer eskaeras SPARQL sigue una configuración parecida a stardog.
Para instalarlo me he basado en el siguiente tutorial: https://www.youtube.com/watch?v=kwB_53ju4_c
Lo de la URI lo he sacado del siguiente link: https://jena.apache.org/documentation/fuseki2/soh.html

**Comment by mikel-egana-aranguren** [comment]
Para JENA tienes que usar TDB: https://jena.apache.org/documentation/tdb/index.html
