### ISSUE TITLE
Configurar GitHub actions para integración continua del código (build, tests, etc)

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#3]
https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/actions/new

**Comment by JonAnderAsua** [comment]
Añadir el requeriments.txt

**Comment by JonAnderAsua** [comment]
Está creado pero me da error a la hora de implementar un módulo propio (cuando runeo los test de normal funciona)

**Comment by JonAnderAsua** [comment]
El error que me da es este: 
`ModuleNotFoundError: No module named 'graphSource'`
Da al importar esto: 
`import graphSource.json2rdf as json2rdf`

**Comment by JonAnderAsua** [comment]
Después de mucho sangre, sudor y lágrimas (sobretodo lágrimas) he conseguido arreglar lo de los módulos, ya te lo explicaré en la siguiente bilera todo lo que he hecho

**Comment by mikel-egana-aranguren** [comment]
Prueba a poner el archivo actions en la rama develop

**Comment by JonAnderAsua** [comment]
Tengo que arreglar unas cosas de los módulos pero en principio ya queda poco para acabar esta issue

**Comment by JonAnderAsua** [comment]
He conseguido que runee bien con los módulos propios. A la hora de instalar las dependencias he añadido el siguiente comando:
pip install -e .
Con esto funciona bien. Cierro el issue (queda pendiente de revisión)
