### ISSUE TITLE
Analizar la tecnología (Grafo y db)

### ISSUE THREAD

**Issue by JonAnderAsua** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#4]
Analizar las tecnologías de Graphdb, RDF, OWL y SPARQL. 
GraphDB: https://www.ontotext.com/products/graphdb/ (Docker hecho por mi: https://github.com/opendata-euskadi/Linked-Data-fase-2/tree/main/graphdb-silk-docker)
GraphDB text mining: https://graphdb.ontotext.com/free/text-mining-plugin.html
RDF, OWL y SPARQL: https://www.w3.org/TR/?tag=data

**Comment by mikel-egana-aranguren** [comment]
https://github.com/mikel-egana-aranguren/MSc-UM-2021-2022-FAIR/blob/8ffe2632b6e324b3be9211b6548bce6966d00ac8/LinkedDataServer/data/CSV2RDF.py

**Comment by mikel-egana-aranguren** [comment]
https://issemantic.net/rdf-visualizer

**Comment by mikel-egana-aranguren** [comment]
```
SELECT ?person
WHERE { 
        ?person wdt:P31 wd:Q5 .
            ?person rdfs:label "Juan Carlos I de España"@es .
}
```
