### ISSUE TITLE
Añadir disclaimer al principio con en Panama Papers

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#7]
![image](https://user-images.githubusercontent.com/3883671/153377260-b4906086-396b-4f82-b3d8-9a3a6120037b.png)

**Comment by mikel-egana-aranguren** [comment]
https://offshoreleaks.icij.org/nodes/10202400

**Comment by mikel-egana-aranguren** [comment]
https://github.com/ICIJ/offshoreleaks-data-packages

**Comment by JonAnderAsua** [comment]
Tengo que usar la etiqueta <footer> para añadirlo. Un ejemplo sería el siguiente 
`<footer>`
`<h3>Licencia de uso</h3>`
`<p>cc-by 2013 Juanan Pereira</p>`
`</footer>`

**Comment by JonAnderAsua** [comment]
He añadido el siguiente texto:  Proiektu honetan erabilitako datuak erabat publikoak dira, eta inoiz ez da esan datu horietan agertzen den edozein pertsona edo erakunde ustelkeriaren errudun denik.

No se si será suficiente, de todas formas igual en esto sí que me tienes que ayudar.

**Comment by mikel-egana-aranguren** [comment]
> Tengo que usar la etiqueta
> 
> para añadirlo. Un ejemplo sería el siguiente
> `<footer>`
> `<h3>Licencia de uso</h3>`
> `<p>cc-by 2013 Juanan Pereira</p>`
> `</footer>`

Esta licencia para que es? Para los datos o para el codigo?

**Comment by mikel-egana-aranguren** [comment]
> He añadido el siguiente texto: Proiektu honetan erabilitako datuak erabat publikoak dira, eta inoiz ez da esan datu horietan agertzen den edozein pertsona edo erakunde ustelkeriaren errudun denik.
> 
> No se si será suficiente, de todas formas igual en esto sí que me tienes que ayudar.

Mas o menos yo diria que esta bien

**Comment by JonAnderAsua** [comment]
> > Tengo que usar la etiqueta
> > para añadirlo. Un ejemplo sería el siguiente
> > `<footer>`
> > `<h3>Licencia de uso</h3>`
> > `<p>cc-by 2013 Juanan Pereira</p>`
> > `</footer>`
> 
> Esta licencia para que es? Para los datos o para el codigo?

Era solo un ejemplo, no voy a usar esa licencia ni nada, era solo para tener en un sitio el uso de la etiqueta footer
