### ISSUE TITLE
Mejoras en JSON2RDF.py

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#8]
Trabajamos con URIs, no con links. Una URI identifica un recurso (Una "cosa": el rey, un medio, la casa real), un link es un enlace.

https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/blob/7ecaebbfcf2153543e4d2d1fee6ac91dc176e624/graphSource/json2rdf.py#L67

- [x] @JonAnderAsua cambiar nombre variable `link` a `uri_base` o algo parecido
- [x]  @JonAnderAsua crear varias URIs base: recurso (`https://ehu.eus/id/`), propiedad (`https://ehu.eus/prop/`), etc.
- [x] @JonAnderAsua cambiar nombres variables a y x
- [x] @JonAnderAsua descomponer metodo setTypeAndLabel
- [x] @JonAnderAsua meter description como rdfs:comment (como rdfs:label)

**Comment by JonAnderAsua** [comment]
He usado los propios identificadores que tienen los elementos del JSON. Por ejemplo antes Juan Carlos era "http://ehu.eus/juan_carlos" y ahora es "http://ehu.eus/persons/juan_carlos"

**Comment by mikel-egana-aranguren** [comment]
Sería más bien "person", no "persons" (Y en todo caso seria "people"). Es mejor que pienses en las URIs que estamos creando como identificadores de entidades, más que como URLs. Por ejemplo en una URL que apunta a un documento "persons" pueden tener sentido, pero en una URI que identifica a una persona no.

**Comment by JonAnderAsua** [comment]
He cambiado ya los links de "persons" con el método fromPersonsToPeople (lineas 83-89)

**Comment by mikel-egana-aranguren** [comment]
Es mejor referirse con propiedad a las cosas, a mí por lo menos me ayuda. Así que intenta no llamar a las URIs "links", si no te lias.

Hay que poner los types en singular, es decir en vez de "people", "person" (`<http://ehu.eus/person/antonio_de_palma>`), en vez de "articles" "article" etc. 

Y también las URIs que sean de "cosas" (article, person) que su URI base sea https://ehu.eus/id/, y brelaciones que sea https://ehu.eus/prop/

**Comment by JonAnderAsua** [comment]
Entonces por ejemplo la URI de Juancar sería https://ehu.eus/id/person/juan_carlos ?

**Comment by mikel-egana-aranguren** [comment]
Eso es

**Comment by JonAnderAsua** [comment]
He cambiado lo que has dicho, lo dejo abierto hasta que le des el visto bueno, en el caso en el que lo des cierralo tú

**Comment by mikel-egana-aranguren** [comment]
El archivo NT esta vacio: https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/blob/feature/sample_data/data/ladonacion.es/grafoa.nt

**Comment by JonAnderAsua** [comment]
Ya está, se me había olvidado descomentar las partes para añadir las tuplas al grafo

**Comment by mikel-egana-aranguren** [comment]
No es "prop/relations", solo "prop", es decir "http://ehu.eus/prop/takes_part". Faltan los rdf:type y los rdfs:label no?
