### ISSUE TITLE
Mejoras en Grafo la donacion

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [mikel-egana-aranguren/TFG-KG-RelacionesClientelares#9]
- [x] @JonAnderAsua Añadir rdfs:label a cada entidad, con el nombre. Por ejemplo `<http://ehu.eus/juan_carlos> rdfs:label "Juan Carlos I de Borbón"@es`. Las URIs completas de rdf, rdfs, xsd, owl etc las sacas de [prefix.cc](prefix.cc)
- [x] @JonAnderAsua Añadir rdf:type cada entidad, usando [Schema](schema.org) como guía. Por ejemplo `<http://ehu.eus/juan_carlos> rdf:type https://schema.org/Person`, `<http://ehu.eus/elconfidencial_2672571> rdf:type <https://schema.org/NewsArticle>`. Las URIs completas de rdf, rdfs, xsd, owl etc las sacas de [prefix.cc](prefix.cc)
- [x] @JonAnderAsua Añadir el type en la URI, por ejemplo la URI para Juan Carlos sería <http://ehu.eus/person/juan_carlos>
- [x] @JonAnderAsua arreglar errores de modelado. Por ejemplo:
  - Una noticia se puede mencionar a sí misma? (https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/blob/7ecaebbfcf2153543e4d2d1fee6ac91dc176e624/data/ladonacion.es/grafoa.nt#L189) 
  - Una noticia participa en Corinna? Como puede una noticia participar en una persona? (https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/blob/7ecaebbfcf2153543e4d2d1fee6ac91dc176e624/data/ladonacion.es/grafoa.nt#L108)
  - La entidad `http://ehu.eus/elconfidencial_2672571` es a la vez una persona (Bastante rara a su vez, por que es padre de los dos componentes de un matrimonio, pareja de un hijo, un padre, y un hermano...), una noticia (Que se menciona a si misma, es decir un bucle muy recursivo muy raro, tipo Matrix), y una institución que esta registrada en UCUM? Como puede una sola cosa de este universo ser todo eso a la vez?

![image](https://user-images.githubusercontent.com/3883671/154045756-1661e4e4-e840-4bc4-8ba4-d4794f00c269.png)

  - Que quiere decir "gives"? "gives to"? 

![image](https://user-images.githubusercontent.com/3883671/154053419-b3f470fa-af4a-474a-a0ed-a55055e0d941.png)

**Comment by mikel-egana-aranguren** [comment]
Faltan los triples rdf:type

**Comment by JonAnderAsua** [comment]
He añadido ya el type y el label en el siguiente método 
`def setTypeAndLabel(a, x): # https://rdflib.readthedocs.io/en/stable/intro_to_creating_rdf.html
#In: URIRef objektu bat / Zein motatako objektua den (pertsona, lekua,...)
#Out: Objektu hori namespace batera esleitu
    global per, ekit, doku, leku, enti, arti,g , entitateak,ekitaldiak,pertsonak,lekuak,erlazioak,iturriak, dokumentuak, artikuluak

    c = None #Type
    d = None #Label

    if(x == "persons"):
        c = per
        d = getLabel(a.split("/")[-1],x, pertsonak)
    elif(x == "events"):
        c = ekit
        d = getLabel(a.split("/")[-1], x, ekitaldiak)
    elif(x == "documents"):
        c = doku
        d = getLabel(a.split("/")[-1], x, dokumentuak)
    elif(x == "places"):
        c = leku
        d = getLabel(a.split("/")[-1], x, lekuak)
    elif(x == "entities"):
        c = enti
        d = getLabel(a.split("/")[-1], x, entitateak)
    else:
        c = arti
        d = getLabel(a.split("/")[-1], "articles", artikuluak) #Lo meto a mano por sea caso

    tuplaType = (a,RDF.type,c)
    tuplaLabel = (a,RDFS.label,Literal(d))

    print(tuplaType)
    print(tuplaLabel)
    g.add(tuplaType)
    g.add(tuplaLabel)`

**Comment by mikel-egana-aranguren** [comment]
OK tiene buena pinta. A ver cuando lo carguemos en GraphDB

(No son tuplas, son triples)
